import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, UserButton } from "@clerk/nextjs";
import NavBar from "@/components/layout/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressContentEditableWarning>  
      <body className={inter.className}>
        {/* <header className="flex justify-between">
          <h1>BabylonBookings</h1>
            <UserButton showName/>
          </header> */}
          <NavBar/>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
